In [1]:
import numpy as np
import pandas as pd
import random

### 1) How likely is it that you roll doubles when rolling two dice?

In [3]:
# convert to array
nrows = n_simulations = 100_000
ncols = n_dice_rolled = 2

In [24]:
np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols)

array([1, 2, 4, ..., 6, 3, 3])

In [25]:
np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

array([[6, 2],
       [5, 1],
       [3, 3],
       ...,
       [3, 5],
       [5, 1],
       [6, 6]])

In [26]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

In [27]:
# convert to data frame
pd.DataFrame(rolls)

0  1
0      6  4
1      3  2
2      3  2
3      6  2
4      6  1
...   .. ..
99995  4  5
99996  5  1
99997  2  1
99998  1  3
99999  3  4

[100000 rows x 2 columns]

In [28]:
df = pd.DataFrame(rolls)

In [29]:
# add double columnn
df['doubles'] = df[0] == df[1]

In [30]:
df.head()

0  1  doubles
0  6  4    False
1  3  2    False
2  3  2    False
3  6  2    False
4  6  1    False

In [31]:
# get odds of doubles
df.doubles.mean()

0.16521

In [32]:
odds_of_doubles = int(round(df.doubles.mean(),2) * 100)

In [33]:
print(f'The odds of rolling doubles on two fair 6 sided dice are {odds_of_doubles}%')

The odds of rolling doubles on two fair 6 sided dice are 17%


In [39]:
# All together

nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 2       # set columns to number of dice rolled in each simulation

# create data frame with each row representing a simulation and each column representing a dice roll in the simulation
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols) 

# convert to data frame
df = pd.DataFrame(rolls)

# add double columnn
df['doubles'] = df[0] == df[1]

# get mean of doubles column
# format and print results
odds_of_doubles = int(round(df.doubles.mean(),2) * 100)

print(f'The odds of rolling doubles on two fair 6 sided dice are {odds_of_doubles}%')

The odds of rolling doubles on two fair 6 sided dice are 17%


### 2) If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [73]:
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 8       # set columns to number of dice rolled in each simulation

In [74]:
# create data frame with each row representing a simulation and each column representing a dice roll in the simulation
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)
rolls

array([[False,  True,  True, ...,  True,  True, False],
       [False, False, False, ...,  True,  True, False],
       [ True,  True,  True, ...,  True, False,  True],
       ...,
       [ True, False,  True, ..., False, False,  True],
       [ True, False, False, ..., False,  True,  True],
       [ True, False, False, ...,  True, False, False]])

In [59]:
# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0      1      2      3      4      5      6      7
0  False  False   True  False   True   True   True  False
1   True   True   True   True  False   True  False   True
2  False   True   True  False   True   True   True   True
3   True  False  False   True   True  False  False   True
4  False  False  False  False  False   True   True  False

In [60]:
# add calculation columnn
df['number_of_heads'] = df.sum(axis=1)
df['exactly_three_heads'] = df.number_of_heads == 3
df['three_or_more_heads'] = df.number_of_heads >= 3
df.head()

0      1      2      3      4      5      6      7  number_of_heads  \
0  False  False   True  False   True   True   True  False                4   
1   True   True   True   True  False   True  False   True                6   
2  False   True   True  False   True   True   True   True                6   
3   True  False  False   True   True  False  False   True                4   
4  False  False  False  False  False   True   True  False                2   

   exactly_three_heads  three_or_more_heads  
0                False                 True  
1                False                 True  
2                False                 True  
3                False                 True  
4                False                False

In [66]:
# get mean of T/F calculation column

In [61]:
df.exactly_three_heads.mean()

0.22172

In [62]:
df.three_or_more_heads.mean()

0.85854

In [65]:
# get mean of calculation columns
# format and print results
odds_of_three_heads = int(round(df.exactly_three_heads.mean(),2) * 100)
odds_of_three_or_more_heads = int(round(df.three_or_more_heads.mean(),2) * 100)

print(f'The odds of getting exactly three heads when flipping five coins is {odds_of_three_heads}%')
print(f'The odds of gettng three or more heads in the same five flips is {odds_of_three_or_more_heads}%')

The odds of getting exactly three heads when flipping five coins is 22%
The odds of gettng three or more heads in the same five flips is 86%


In [68]:
# All together
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 8       # set columns to number of dice rolled in each simulation

# create data frame with each row representing a simulation and each column representing a dice roll in the simulation
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnn
df['number_of_heads'] = df.sum(axis=1)
df['exactly_three_heads'] = df.number_of_heads == 3
df['three_or_more_heads'] = df.number_of_heads >= 3

# get mean of calculation True/False columns
# format and print results
odds_of_three_heads = int(round(df.exactly_three_heads.mean(),2) * 100)
odds_of_three_or_more_heads = int(round(df.three_or_more_heads.mean(),2) * 100)

print(f'The odds of getting exactly three heads when flipping five coins is {odds_of_three_heads}%')
print(f'The odds of gettng three or more heads in the same five flips is {odds_of_three_or_more_heads}%')

The odds of getting exactly three heads when flipping five coins is 22%
The odds of gettng three or more heads in the same five flips is 86%


### 3) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [77]:
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 2       # set columns to number of bilboards in each simulation

In [78]:
# create data frame with each row representing a simulation and each column representing a bilboard in the simulation
rolls = np.random.choice(["DS","WEB","WEB","WEB"], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0    1
0  WEB  WEB
1  WEB  WEB
2  WEB   DS
3  WEB  WEB
4  WEB  WEB

In [79]:
# add calculation columnn
df['both_ds'] = (df[0] == "DS") & (df[1] == "DS")

df.both_ds.mean()

0.06151

In [80]:
# get mean of calculation True/False columns
# format and print results
both_ds = int(round(df.both_ds.mean(),2) * 100)


print(f'The odds of both billboards being Data Science are {both_ds}%')

The odds of both billboards being Data Science are 6%


In [81]:
# All together
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 2       # set columns to number of bilboards in each simulation

# create data frame with each row representing a simulation and each column representing a bilboard in the simulation
rolls = np.random.choice(["DS","WEB","WEB","WEB"], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnn
df['both_ds'] = (df[0] == "DS") & (df[1] == "DS")

# get mean of calculation True/False columns
# format and print results
both_ds = int(round(df.both_ds.mean(),2) * 100)


print(f'The odds of both billboards being Data Science are {both_ds}%')

The odds of both billboards being Data Science are 6%


### 4) Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [91]:
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 5       # set columns to number of days in each simulation

In [92]:
# create array with each row representing a simulation and each column representing a day in the simulation
rolls = np.random.uniform(1.5, 4.5, nrows * ncols).astype(int).reshape(nrows, ncols)
rolls

array([[3, 2, 2, 1, 2],
       [3, 4, 4, 3, 3],
       [1, 3, 4, 3, 4],
       ...,
       [3, 3, 1, 2, 2],
       [3, 4, 1, 2, 2],
       [4, 2, 1, 2, 4]])

In [93]:
# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0  1  2  3  4
0  3  2  2  1  2
1  3  4  4  3  3
2  1  3  4  3  4
3  4  1  3  3  2
4  3  4  4  3  4

In [94]:
# add calculation columnns
df['total_pop_tarts'] = df.sum(axis=1)
df['pop_tarts_remain'] = df['total_pop_tarts'] < 17
df.head()

0  1  2  3  4  total_pop_tarts  pop_tarts_remain
0  3  2  2  1  2               10              True
1  3  4  4  3  3               17             False
2  1  3  4  3  4               15              True
3  4  1  3  3  2               13              True
4  3  4  4  3  4               18             False

In [95]:
df['pop_tarts_remain'].mean()

0.97061

In [96]:
# get mean of calculation True/False columns
# format and print results
tarts = int(round(df['pop_tarts_remain'].mean(),2) * 100)


print(f'The odds of being able to by a PopTart in the afternoon on friday are {tarts}%')

The odds of being able to by a PopTart in the afternoon on friday are 97%


In [97]:
# All together
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 5       # set columns to number of days in each simulation

# create array with each row representing a simulation and each column representing a day in the simulation
rolls = np.random.uniform(1.5, 4.5, nrows * ncols).astype(int).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnns
df['total_pop_tarts'] = df.sum(axis=1)
df['pop_tarts_remain'] = df['total_pop_tarts'] < 17

# get mean of calculation True/False columns
# format and print results
tarts = int(round(df['pop_tarts_remain'].mean(),2) * 100)


print(f'The odds of being able to by a PopTart in the afternoon on friday are {tarts}%')

The odds of being able to by a PopTart in the afternoon on friday are 97%


### 5) Men have an average height of 178 cm and standard deviation of 8cm. Women have a mean of 170, sd = 6cm. If a man and woman are chosen at random, P(woman taller than man)?

### 6) When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.

### a) What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### b) What is the probability that we observe an installation issue within the first 150 students that download anaconda?

### 5) How likely is it that 450 students all download anaconda without an issue?

### 6) There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

### 7) How likely is it that a food truck will show up sometime this week?

### 8) If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?