In [1]:
import numpy as np
import pandas as pd
import random

### 1) How likely is it that you roll doubles when rolling two dice?

In [3]:
# convert to array
nrows = n_simulations = 100_000
ncols = n_dice_rolled = 2

In [24]:
np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols)

array([1, 2, 4, ..., 6, 3, 3])

In [25]:
np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

array([[6, 2],
       [5, 1],
       [3, 3],
       ...,
       [3, 5],
       [5, 1],
       [6, 6]])

In [26]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

In [27]:
# convert to data frame
pd.DataFrame(rolls)

0  1
0      6  4
1      3  2
2      3  2
3      6  2
4      6  1
...   .. ..
99995  4  5
99996  5  1
99997  2  1
99998  1  3
99999  3  4

[100000 rows x 2 columns]

In [28]:
df = pd.DataFrame(rolls)

In [29]:
# add double columnn
df['doubles'] = df[0] == df[1]

In [30]:
df.head()

0  1  doubles
0  6  4    False
1  3  2    False
2  3  2    False
3  6  2    False
4  6  1    False

In [31]:
# get odds of doubles
df.doubles.mean()

0.16521

In [32]:
odds_of_doubles = int(round(df.doubles.mean(),2) * 100)

In [33]:
print(f'The odds of rolling doubles on two fair 6 sided dice are {odds_of_doubles}%')

The odds of rolling doubles on two fair 6 sided dice are 17%


In [39]:
# All together

nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 2       # set columns to number of dice rolled in each simulation

# create data frame with each row representing a simulation and each column representing a dice roll in the simulation
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols) 

# convert to data frame
df = pd.DataFrame(rolls)

# add double columnn
df['doubles'] = df[0] == df[1]

# get mean of doubles column
# format and print results
odds_of_doubles = int(round(df.doubles.mean(),2) * 100)

print(f'The odds of rolling doubles on two fair 6 sided dice are {odds_of_doubles}%')

The odds of rolling doubles on two fair 6 sided dice are 17%


### 2) If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [73]:
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 8       # set columns to number of dice rolled in each simulation

In [74]:
# create data frame with each row representing a simulation and each column representing a dice roll in the simulation
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)
rolls

array([[False,  True,  True, ...,  True,  True, False],
       [False, False, False, ...,  True,  True, False],
       [ True,  True,  True, ...,  True, False,  True],
       ...,
       [ True, False,  True, ..., False, False,  True],
       [ True, False, False, ..., False,  True,  True],
       [ True, False, False, ...,  True, False, False]])

In [59]:
# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0      1      2      3      4      5      6      7
0  False  False   True  False   True   True   True  False
1   True   True   True   True  False   True  False   True
2  False   True   True  False   True   True   True   True
3   True  False  False   True   True  False  False   True
4  False  False  False  False  False   True   True  False

In [60]:
# add calculation columnn
df['number_of_heads'] = df.sum(axis=1)
df['exactly_three_heads'] = df.number_of_heads == 3
df['three_or_more_heads'] = df.number_of_heads >= 3
df.head()

0      1      2      3      4      5      6      7  number_of_heads  \
0  False  False   True  False   True   True   True  False                4   
1   True   True   True   True  False   True  False   True                6   
2  False   True   True  False   True   True   True   True                6   
3   True  False  False   True   True  False  False   True                4   
4  False  False  False  False  False   True   True  False                2   

   exactly_three_heads  three_or_more_heads  
0                False                 True  
1                False                 True  
2                False                 True  
3                False                 True  
4                False                False

In [66]:
# get mean of T/F calculation column

In [61]:
df.exactly_three_heads.mean()

0.22172

In [62]:
df.three_or_more_heads.mean()

0.85854

In [65]:
# get mean of calculation columns
# format and print results
odds_of_three_heads = int(round(df.exactly_three_heads.mean(),2) * 100)
odds_of_three_or_more_heads = int(round(df.three_or_more_heads.mean(),2) * 100)

print(f'The odds of getting exactly three heads when flipping five coins is {odds_of_three_heads}%')
print(f'The odds of gettng three or more heads in the same five flips is {odds_of_three_or_more_heads}%')

The odds of getting exactly three heads when flipping five coins is 22%
The odds of gettng three or more heads in the same five flips is 86%


In [68]:
# All together
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 8       # set columns to number of dice rolled in each simulation

# create data frame with each row representing a simulation and each column representing a dice roll in the simulation
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnn
df['number_of_heads'] = df.sum(axis=1)
df['exactly_three_heads'] = df.number_of_heads == 3
df['three_or_more_heads'] = df.number_of_heads >= 3

# get mean of calculation True/False columns
# format and print results
odds_of_three_heads = int(round(df.exactly_three_heads.mean(),2) * 100)
odds_of_three_or_more_heads = int(round(df.three_or_more_heads.mean(),2) * 100)

print(f'The odds of getting exactly three heads when flipping five coins is {odds_of_three_heads}%')
print(f'The odds of gettng three or more heads in the same five flips is {odds_of_three_or_more_heads}%')

The odds of getting exactly three heads when flipping five coins is 22%
The odds of gettng three or more heads in the same five flips is 86%


### 3) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [77]:
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 2       # set columns to number of bilboards in each simulation

In [78]:
# create data frame with each row representing a simulation and each column representing a bilboard in the simulation
rolls = np.random.choice(["DS","WEB","WEB","WEB"], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0    1
0  WEB  WEB
1  WEB  WEB
2  WEB   DS
3  WEB  WEB
4  WEB  WEB

In [79]:
# add calculation columnn
df['both_ds'] = (df[0] == "DS") & (df[1] == "DS")

df.both_ds.mean()

0.06151

In [80]:
# get mean of calculation True/False columns
# format and print results
both_ds = int(round(df.both_ds.mean(),2) * 100)


print(f'The odds of both billboards being Data Science are {both_ds}%')

The odds of both billboards being Data Science are 6%


In [81]:
# All together
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 2       # set columns to number of bilboards in each simulation

# create data frame with each row representing a simulation and each column representing a bilboard in the simulation
rolls = np.random.choice(["DS","WEB","WEB","WEB"], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnn
df['both_ds'] = (df[0] == "DS") & (df[1] == "DS")

# get mean of calculation True/False columns
# format and print results
both_ds = int(round(df.both_ds.mean(),2) * 100)


print(f'The odds of both billboards being Data Science are {both_ds}%')

The odds of both billboards being Data Science are 6%


### 4) Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [91]:
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 5       # set columns to number of days in each simulation

In [92]:
# create array with each row representing a simulation and each column representing a day in the simulation
rolls = np.random.uniform(1.5, 4.5, nrows * ncols).astype(int).reshape(nrows, ncols)
rolls

array([[3, 2, 2, 1, 2],
       [3, 4, 4, 3, 3],
       [1, 3, 4, 3, 4],
       ...,
       [3, 3, 1, 2, 2],
       [3, 4, 1, 2, 2],
       [4, 2, 1, 2, 4]])

In [93]:
# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0  1  2  3  4
0  3  2  2  1  2
1  3  4  4  3  3
2  1  3  4  3  4
3  4  1  3  3  2
4  3  4  4  3  4

In [94]:
# add calculation columnns
df['total_pop_tarts'] = df.sum(axis=1)
df['pop_tarts_remain'] = df['total_pop_tarts'] < 17
df.head()

0  1  2  3  4  total_pop_tarts  pop_tarts_remain
0  3  2  2  1  2               10              True
1  3  4  4  3  3               17             False
2  1  3  4  3  4               15              True
3  4  1  3  3  2               13              True
4  3  4  4  3  4               18             False

In [95]:
df['pop_tarts_remain'].mean()

0.97061

In [96]:
# get mean of calculation True/False columns
# format and print results
tarts = int(round(df['pop_tarts_remain'].mean(),2) * 100)


print(f'The odds of being able to by a PopTart in the afternoon on friday are {tarts}%')

The odds of being able to by a PopTart in the afternoon on friday are 97%


In [97]:
# All together
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 5       # set columns to number of days in each simulation

# create array with each row representing a simulation and each column representing a day in the simulation
rolls = np.random.uniform(1.5, 4.5, nrows * ncols).astype(int).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnns
df['total_pop_tarts'] = df.sum(axis=1)
df['pop_tarts_remain'] = df['total_pop_tarts'] < 17

# get mean of calculation True/False columns
# format and print results
tarts = int(round(df['pop_tarts_remain'].mean(),2) * 100)


print(f'The odds of being able to by a PopTart in the afternoon on friday are {tarts}%')

The odds of being able to by a PopTart in the afternoon on friday are 97%


### 5) Men have an average height of 178 cm and standard deviation of 8cm. Women have a mean of 170, sd = 6cm. If a man and woman are chosen at random, P(woman taller than man)?

In [ ]:
# create arrays of veriables
male_hights = np.random.normal(178, 8, 100_000)
female_hights = np.random.normal(170, 6, 100_000)

In [98]:
male_hights

array([177.45109596, 175.23025193, 191.83268588, ..., 192.06285681,
       163.24718859, 184.3162796 ])

In [103]:
female_hights

array([161.21275394, 168.54842788, 168.9514588 , ..., 173.59025236,
       179.1192922 , 165.85263339])

In [104]:
# convert array to data frame
df = pd.DataFrame({"male_hights" : male_hights,
                   "female_hights" : female_hights})

df.head()

male_hights  female_hights
0   177.451096     161.212754
1   175.230252     168.548428
2   191.832686     168.951459
3   175.231616     159.225250
4   176.178865     171.559581

In [106]:
# add calculated column
df['female_is_taller'] = df.female_hights > df.male_hights
df.head()

male_hights  female_hights  female_is_taller
0   177.451096     161.212754             False
1   175.230252     168.548428             False
2   191.832686     168.951459             False
3   175.231616     159.225250             False
4   176.178865     171.559581             False

In [107]:
# get mean of female_is_taller
df['female_is_taller'].mean()

0.20925

In [110]:
# All together
# create arrays of veriables
male_hights = np.random.normal(178, 8, 100_000)
female_hights = np.random.normal(170, 6, 100_000)

# convert array to data frame
df = pd.DataFrame({"male_hights" : male_hights,
                   "female_hights" : female_hights})

# add calculated column
df['female_is_taller'] = df.female_hights > df.male_hights

# get mean of female_is_taller
df['female_is_taller'].mean()

# get mean of calculation True/False columns
# format and print results
taller_female = int(round(df['female_is_taller'].mean(),2) * 100)

print(f"The probability of a woman, chosen at random, being taller than a man, chosen at random is {taller_female}%")

The probability of a woman, chosen at random, being taller than a man, chosen at random is 21%


### 6) When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.

### a) What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [134]:
nrows = n_simulations = 100_000 # set rows to number of simulations
ncols = n_dice_rolled = 50      # set columns to number of days in each simulation

In [135]:
# create array with each row representing a simulation and each column representing a student in the simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)
installs

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [136]:
# convert to data frame
df = pd.DataFrame(installs)
df.head()

0      1      2      3      4      5      6      7      8      9   ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      40     41     42     43     44     45     46     47     48     49  
0  False  False  False  False  False  False  False  False  False  False  
1  False  False  False  False  False  False  False  False  False  False  
2  False  False  False  False  False  False  False  False  False  False  
3  False  False  False  False  False  False  False  False  False  False  
4  False  False  False  False  False  False  False  False  False  False  

[5 rows x 50 columns]

In [139]:
# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0
df.head()

0      1      2      3      4      5      6      7      8      9  ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      41     42     43     44     45     46     47     48     49  \
0  False  False  False  False  False  False  False  False  False   
1  False  False  False  False  False  False  False  False  False   
2  False  False  False  False  False  False  False  False  False   
3  False  False  False  False  False  False  False  False  False   
4  False  False  False  False  False  False  False  False  False   

   has_no_problem  
0            True  
1            True  
2           False  
3            True  
4            True  

[5 rows x 51 columns]

In [140]:
df['has_no_problem'].mean()

0.81944

In [142]:
# All together
nrows = 100_000 # set rows to number of simulations
ncols = 50      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

print(f'The odds of 50 students dowloading Anaconda without a problem are {problems}%')

The odds of 50 students dowloading Anaconda without a problem are 82%


### b) What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [144]:
# All together
nrows = 100_000 # set rows to number of simulations
ncols = 150      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_a_problem'] = df.sum(axis=1) > 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_a_problem'].mean(),2) * 100)

print(f'The odds of a problem occuring in the first 150 instllations is {problems}%')

The odds of a problem occuring in the first 150 instllations is 45%


### 5) How likely is it that 450 students all download anaconda without an issue?

In [146]:
# All together
nrows = 100_000 # set rows to number of simulations
ncols = 450      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

print(f'The odds of 450 instllations occuring without an issue is {problems}%')

The odds of 450 instllations occuring without an issue is 16%


### 6) There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [ ]:
nrows = 100_000 # set rows to number of simulations
ncols = 3      # set columns to number of students in each simulation

In [ ]:
# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)
sightings

In [ ]:
# convert to data frame
df = pd.DataFrame(sightings)
df.head()

In [ ]:
# add calculation columnns
df['not_sighted_three_days'] = df.sum(axis=1) == 0
df.head()

In [148]:
# get mean of calculation True/False columns
# format and print results
trucks = int(round(df['not_sighted_three_days'].mean(),2) * 100)

print(f'The odds of not seeing a food truck in Travis Park for three days is {trucks}%')

The odds of not seeing a food truck in Travis Park in three days is 3%


### 7) How likely is it that a food truck will show up sometime this week?

In [177]:
# Remaining week days
nrows = 100_000 # set rows to number of simulations
ncols = 2      # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['not_sighted_two_days'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
trucks = int(round(df['not_sighted_two_days'].mean(),4) * 100)

print(f'The odds of not seeing a food truck in Travis Park for {ncols} days is {trucks}%')

The odds of not seeing a food truck in Travis Park for 2 days is 9%


In [178]:
nrows = 100_000 # set rows to number of simulations
ncols = 5      # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['not_sighted_five_days'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
trucks = round(df['not_sighted_five_days'].mean(),4) * 100

print(f'The odds of not seeing a food truck in Travis Park for {ncols} days is {trucks}%')

The odds of not seeing a food truck in Travis Park for 5 days is 0.24%


In [179]:
nrows = 100_000 # set rows to number of simulations
ncols = 7       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['not_sighted_three_days'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
trucks = round(df['not_sighted_three_days'].mean(),4) * 100

print(f'The odds of not seeing a food truck in Travis Park for {ncols} days is {trucks}%')

The odds of not seeing a food truck in Travis Park for 7 days is 0.02%


### 8) If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [166]:
nrows = 100_000 # set rows to number of simulations
ncols = 23       # set columns to number of students in each simulation

In [167]:
# create array with each row representing a simulation and each column representing a student in the simulation
birth_days = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)
birth_days

array([[ 39, 259,  43, ..., 355, 255, 278],
       [173, 188, 359, ..., 221, 278, 158],
       [114, 215,  19, ...,  21,  59, 164],
       ...,
       [300, 323,  35, ...,  26, 245, 217],
       [199, 217, 303, ..., 360, 332,  48],
       [241,   5,  60, ..., 358, 172, 331]])

In [168]:
# convert to data frame
df = pd.DataFrame(birth_days)
df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   39  259   43    7  179  358  364   63  324   33  ...   93   29   97   57   
1  173  188  359   70  129  342   75   53  138   33  ...  104  308  288  115   
2  114  215   19   13   48  281    8  284  166   99  ...  117  283  147  175   
3  257  351  180  253  304  222  281  267  125  141  ...  352   59  215   83   
4  211   94  312  272   71  238  313  148  297  286  ...  302  208  162  165   

    17   18   19   20   21   22  
0  221  281  240  355  255  278  
1  276  343   31  221  278  158  
2  346  307   56   21   59  164  
3  188  179  317   28  280  191  
4  221  308  178   78   93  178  

[5 rows x 23 columns]

In [169]:
# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1
df.head()

0    1    2    3    4    5    6    7    8    9  ...   15   16   17   18  \
0   39  259   43    7  179  358  364   63  324   33  ...   97   57  221  281   
1  173  188  359   70  129  342   75   53  138   33  ...  288  115  276  343   
2  114  215   19   13   48  281    8  284  166   99  ...  147  175  346  307   
3  257  351  180  253  304  222  281  267  125  141  ...  215   83  188  179   
4  211   94  312  272   71  238  313  148  297  286  ...  162  165  221  308   

    19   20   21   22  at_least_two_matching_birthdays  \
0  240  355  255  278                            False   
1   31  221  278  158                             True   
2   56   21   59  164                            False   
3  317   28  280  191                            False   
4  178   78   93  178                             True   

   exactly_two_matching_birthdays  
0                           False  
1                           False  
2                           False  
3                           False  
4                           False  

[5 rows x 25 columns]

In [170]:
# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 23 people having exactly least two people that share a birthday are 13%


In [171]:
nrows = 100_000 # set rows to number of simulations
ncols = 23       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly least two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 23 people having at least two people that share a birthday are 50%
The odds of a room of 23 people having exactly least two people that share a birthday are 13%


### 20 people

In [172]:
nrows = 100_000 # set rows to number of simulations
ncols = 20       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly least two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 20 people having exactly least two people that share a birthday are 9%


### 40 people

In [173]:
nrows = 100_000 # set rows to number of simulations
ncols = 40       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 40 people having at least two people that share a birthday are 89%
The odds of a room of 40 people having exactly least two people that share a birthday are 28%
